import { Property } from './PropertyCard';

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Modern 2-Bedroom Apartment in Annex',
    price: '35,000',
    location: 'Annex, Eldoret',
    beds: 2,
    baths: 2,
    sqft: 950,
    image: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBhcGFydG1lbnQlMjBidWlsZGluZ3xlbnwxfHx8fDE3NjM0MjAwOTl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    type: 'Apartment',
    status: 'New',
    listingType: 'For Rent',
    description: 'Beautiful modern apartment with stunning views and all amenities. Walking distance to Zion Mall and excellent public transport links.',
  },
  {
    id: '2',
    title: 'Spacious 3-Bedroom House Near Zion Mall',
    price: '65,000',
    location: 'Zion Estate, Eldoret',
    beds: 3,
    baths: 2,
    sqft: 1400,
    image: 'https://images.unsplash.com/photo-1706808849780-7a04fbac83ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBob3VzZSUyMGV4dGVyaW9yfGVufDF8fHx8MTc2MzQzOTY3MXww&ixlib=rb-4.1.0&q=80&w=1080',
    type: 'House for Rent',
    status: 'Featured',
    listingType: 'For Rent',
    description: 'Luxurious family home with spacious garden, modern kitchen, and secure compound. Perfect for families.',
  },
  {
    id: '3',
    title: 'Affordable Bedsitter in Eldoret CBD',
    price: '12,000',
    location: 'CBD, Eldoret',
    beds: 1,
    baths: 1,
    sqft: 400,
    image: 'https://images.unsplash.com/photo-1563418536419-3a3ad6ef5efd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb250ZW1wb3JhcnklMjBhcGFydG1lbnQlMjBpbnRlcmlvcnxlbnwxfHx8fDE3NjM0OTM1NDR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    type: 'Bedsitter',
    listingType: 'For Rent',
    description: 'Cozy bedsitter in the heart of Eldoret CBD. Perfect for students or young professionals. Close to all amenities.',
  },
  {
    id: '4',
    title: 'Student Housing Near MTRH',
    price: '10,000',
    location: 'Langas, Eldoret',
    beds: 1,
    baths: 1,
    sqft: 350,
    image: 'https://images.unsplash.com/photo-1761944807298-673a32910e90?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZXNpZGVudGlhbCUyMGJ1aWxkaW5nJTIwZmFjYWRlfGVufDF8fHx8MTc2MzQ5MzU0NHww&ixlib=rb-4.1.0&q=80&w=1080',
    listingType: 'For Rent',
    type: 'Student Housing',
    status: 'New',
    description: 'Affordable student accommodation near MTRH and Moi University teaching hospital. Safe and secure.',
  },
  {
    id: '5',
    title: 'Luxury 4-Bedroom House in Pioneer',
    price: '4,500,000',
    location: 'Pioneer, Eldoret',
    beds: 4,
    baths: 3,
    sqft: 2200,
    image: 'https://images.unsplash.com/photo-1627141234469-24711efb373c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBob3VzZSUyMGFyY2hpdGVjdHVyZXxlbnwxfHx8fDE3NjMzNzg4NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    type: 'House for Sale',
    status: 'Featured',
    listingType: 'For Sale',
    description: 'Stunning modern home with premium finishes, large compound, and all modern conveniences. Prime location in Pioneer.',
  },
  {
    id: '6',
    title: 'Short-term Rental Near Rupa Mall',
    price: '3,500',
    location: 'Rupa Mall Area, Eldoret',
    beds: 1,
    baths: 1,
    sqft: 500,
    image: 'https://images.unsplash.com/photo-1738767227236-c0999010e35e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1cmJhbiUyMHJlc2lkZW50aWFsJTIwYnVpbGRpbmd8ZW58MXx8fHwxNzYzNDYxNjU5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    type: 'Short Term',
    listingType: 'For Rent',
    description: 'Fully furnished short-term rental perfect for business travelers. Daily or weekly rates available.',
  },
  {
    id: '7',
    title: 'Commercial Office Space in CBD',
    price: '80,000',
    location: 'CBD, Eldoret',
    beds: 0,
    baths: 2,
    sqft: 1200,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZWFsJTIwZXN0YXRlJTIwcHJvcGVydHl8ZW58MXx8fHwxNzYzMzk2ODY1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    type: 'Commercial',
    status: 'Featured',
    listingType: 'For Rent',
    description: 'Prime office space in Eldoret CBD with parking, security, and excellent visibility.',
  },
  {
    id: '8',
    title: '1-Bedroom Apartment in West Indies',
    price: '22,000',
    location: 'West Indies, Eldoret',
    beds: 1,
    baths: 1,
    sqft: 650,
    image: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcGFydG1lbnQlMjBjb21wbGV4fGVufDF8fHx8MTc2MzM4NjQ2NXww&ixlib=rb-4.1.0&q=80&w=1080',
    type: 'Apartment',
    status: 'New',
    listingType: 'For Rent',
    description: 'Cozy 1-bedroom in quiet West Indies neighborhood. Modern amenities and secure parking.',
  },
  {
    id: '9',
    title: 'Residential Plot in Kimumu',
    price: '2,200,000',
    location: 'Kimumu, Eldoret',
    beds: 0,
    baths: 0,
    sqft: 4500,
    image: 'https://images.unsplash.com/photo-1627141234469-24711efb373c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBob3VzZSUyMGFyY2hpdGVjdHVyZXxlbnwxfHx8fDE3NjMzNzg4NjZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    type: 'Land',
    listingType: 'For Sale',
    description: '50x90 residential plot in upcoming Kimumu area. Ready title deed and clean documentation.',
  },
  {
    id: '10',
    title: '3-Bedroom Apartment in Elgon View',
    price: '45,000',
    location: 'Elgon View, Eldoret',
    beds: 3,
    baths: 2,
    sqft: 1100,
    image: 'https://images.unsplash.com/photo-1706808849780-7a04fbac83ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBob3VzZSUyMGV4dGVyaW9yfGVufDF8fHx8MTc2MzQzOTY3MXww&ixlib=rb-4.1.0&q=80&w=1080',
    type: 'Apartment',
    listingType: 'For Rent',
    description: 'Spacious apartment with panoramic views of Mount Elgon. Family-friendly estate with playground.',
  },
  {
    id: '11',
    title: '2-Bedroom Under Construction',
    price: '28,000',
    location: 'Annex, Eldoret',
    beds: 2,
    baths: 2,
    sqft: 850,
    image: 'https://images.unsplash.com/photo-1761944807298-673a32910e90?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZXNpZGVudGlhbCUyMGJ1aWxkaW5nJTIwZmFjYWRlfGVufDF8fHx8MTc2MzQ5MzU0NHww&ixlib=rb-4.1.0&q=80&w=1080',
    type: 'Under Construction',
    status: 'New',
    listingType: 'For Rent',
    description: 'Brand new 2-bedroom apartments under construction. Move-in ready in 3 months. Book now!',
  },
  {
    id: '12',
    title: 'Warehouse in Industrial Area',
    price: '150,000',
    location: 'Industrial Area, Eldoret',
    beds: 0,
    baths: 1,
    sqft: 3000,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZWFsJTIwZXN0YXRlJTIwcHJvcGVydHl8ZW58MXx8fHwxNzYzMzk2ODY1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    type: 'Commercial',
    listingType: 'For Rent',
    description: 'Large warehouse with loading bay, high ceilings, and 24/7 security. Perfect for storage or light manufacturing.',
  },
];

export const successStories = [
  {
    id: 1,
    name: 'James Kipchoge',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    role: 'First Time Homebuyer',
    challenge: 'I was overwhelmed searching for my first apartment in Eldoret. There were too many options and I didn\'t know which areas were safe and affordable.',
    solution: 'Eldoret House Hunters made the process so easy! They understood my budget and preferences, showed me several great options in Annex, and I found my dream 2-bedroom apartment within a week. The team was professional and supportive throughout.',
    memberSince: 'Jan 2024',
  },
  {
    id: 2,
    name: 'Grace Wanjiku',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    role: 'Property Seller',
    challenge: 'Selling my 3-bedroom house in Pioneer was stressful. I had listed it with other agents for months with no serious buyers, and I was getting desperate.',
    solution: 'Within 2 weeks of listing with Eldoret House Hunters, I had multiple offers! They marketed my property professionally, brought serious buyers, and I got an excellent price. The entire process was smooth and stress-free.',
    memberSince: 'Mar 2023',
  },
  {
    id: 3,
    name: 'David Mutai',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
    role: 'University Student',
    challenge: 'Finding affordable and safe student housing near campus was a nightmare. Most bedsitters were either too expensive or in questionable neighborhoods.',
    solution: 'I found the perfect bedsitter through Eldoret House Hunters! It\'s affordable, close to campus, and in a secure area. The landlord is also very responsive. I recommend them to all my classmates now!',
    memberSince: 'Jul 2024',
  },
];

export const neighborhoods = [
  {
    id: 1,
    name: 'Eldoret CBD',
    description: 'Heart of the city with excellent amenities and transport',
    avgRent: '15,000 - 40,000',
    avgSale: '3M - 8M',
    schools: ['Eldoret Primary', 'Hill School'],
    shopping: ['Zion Mall', 'Rupa Mall', 'Naivas'],
    transport: 'Excellent matatu routes',
    safety: 'High security presence',
  },
  {
    id: 2,
    name: 'Annex',
    description: 'Popular residential area with modern apartments',
    avgRent: '25,000 - 50,000',
    avgSale: '4M - 10M',
    schools: ['Annex Primary', 'Eldoret Academy'],
    shopping: ['Zion Mall (5 min)', 'Local shops'],
    transport: 'Good matatu access',
    safety: 'Gated communities',
  },
  {
    id: 3,
    name: 'Pioneer',
    description: 'Premium residential area with luxury homes',
    avgRent: '60,000 - 150,000',
    avgSale: '8M - 25M',
    schools: ['Brookhouse School', 'Pioneer Academy'],
    shopping: ['Close to all malls', 'High-end retail'],
    transport: 'Private transport recommended',
    safety: 'Very secure, gated estates',
  },
];
